// <auto-generated />
namespace HomebrewRPG.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class inventoryRework : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inventoryRework));
        
        string IMigrationMetadata.Id
        {
            get { return "202107061928054_inventoryRework"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
