namespace HomebrewRPG.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addedstatstoweaponandwardrobe : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Character", "CurrentHitPoints", c => c.Int(nullable: false));
            AddColumn("dbo.Character", "TempHitPoints", c => c.Int(nullable: false));
            AddColumn("dbo.Character", "PhysicalResistance", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "BlockModifier", c => c.String());
            AddColumn("dbo.WardrobeItem", "Health", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Strength", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Instinct", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Agility", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Intelligence", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Charisma", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "HitPoints", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Sanity", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Dodge", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Reaction", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "BaseProwess", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Magic", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Fate", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Speed", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Endurance", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Constitution", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Athletics", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Tenacity", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Acrobatics", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "SleightOfHand", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Sneak", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Willpower", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Investigation", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Knowledge", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Bravery", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Pilotry", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Insight", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Perception", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Survival", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Faith", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Deception", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Diplomacy", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Intimidation", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Performance", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "Seduction", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Health", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Strength", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Instinct", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Agility", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Intelligence", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Charisma", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "HitPoints", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Sanity", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Dodge", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Reaction", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "BaseProwess", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Magic", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Fate", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Speed", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Endurance", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Constitution", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Athletics", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Tenacity", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Acrobatics", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "SleightOfHand", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Sneak", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Willpower", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Investigation", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Knowledge", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Bravery", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Pilotry", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Insight", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Perception", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Survival", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Faith", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Deception", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Diplomacy", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Intimidation", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Performance", c => c.Int(nullable: false));
            AddColumn("dbo.Weapon", "Seduction", c => c.Int(nullable: false));
            DropColumn("dbo.Character", "DamageResistance");
            DropColumn("dbo.WardrobeItem", "PhysicalBlocking");
            DropColumn("dbo.WardrobeItem", "MagicalBlocking");
        }
        
        public override void Down()
        {
            AddColumn("dbo.WardrobeItem", "MagicalBlocking", c => c.Int(nullable: false));
            AddColumn("dbo.WardrobeItem", "PhysicalBlocking", c => c.Int(nullable: false));
            AddColumn("dbo.Character", "DamageResistance", c => c.Int(nullable: false));
            DropColumn("dbo.Weapon", "Seduction");
            DropColumn("dbo.Weapon", "Performance");
            DropColumn("dbo.Weapon", "Intimidation");
            DropColumn("dbo.Weapon", "Diplomacy");
            DropColumn("dbo.Weapon", "Deception");
            DropColumn("dbo.Weapon", "Faith");
            DropColumn("dbo.Weapon", "Survival");
            DropColumn("dbo.Weapon", "Perception");
            DropColumn("dbo.Weapon", "Insight");
            DropColumn("dbo.Weapon", "Pilotry");
            DropColumn("dbo.Weapon", "Bravery");
            DropColumn("dbo.Weapon", "Knowledge");
            DropColumn("dbo.Weapon", "Investigation");
            DropColumn("dbo.Weapon", "Willpower");
            DropColumn("dbo.Weapon", "Sneak");
            DropColumn("dbo.Weapon", "SleightOfHand");
            DropColumn("dbo.Weapon", "Acrobatics");
            DropColumn("dbo.Weapon", "Tenacity");
            DropColumn("dbo.Weapon", "Athletics");
            DropColumn("dbo.Weapon", "Constitution");
            DropColumn("dbo.Weapon", "Endurance");
            DropColumn("dbo.Weapon", "Speed");
            DropColumn("dbo.Weapon", "Fate");
            DropColumn("dbo.Weapon", "Magic");
            DropColumn("dbo.Weapon", "BaseProwess");
            DropColumn("dbo.Weapon", "Reaction");
            DropColumn("dbo.Weapon", "Dodge");
            DropColumn("dbo.Weapon", "Sanity");
            DropColumn("dbo.Weapon", "HitPoints");
            DropColumn("dbo.Weapon", "Charisma");
            DropColumn("dbo.Weapon", "Intelligence");
            DropColumn("dbo.Weapon", "Agility");
            DropColumn("dbo.Weapon", "Instinct");
            DropColumn("dbo.Weapon", "Strength");
            DropColumn("dbo.Weapon", "Health");
            DropColumn("dbo.WardrobeItem", "Seduction");
            DropColumn("dbo.WardrobeItem", "Performance");
            DropColumn("dbo.WardrobeItem", "Intimidation");
            DropColumn("dbo.WardrobeItem", "Diplomacy");
            DropColumn("dbo.WardrobeItem", "Deception");
            DropColumn("dbo.WardrobeItem", "Faith");
            DropColumn("dbo.WardrobeItem", "Survival");
            DropColumn("dbo.WardrobeItem", "Perception");
            DropColumn("dbo.WardrobeItem", "Insight");
            DropColumn("dbo.WardrobeItem", "Pilotry");
            DropColumn("dbo.WardrobeItem", "Bravery");
            DropColumn("dbo.WardrobeItem", "Knowledge");
            DropColumn("dbo.WardrobeItem", "Investigation");
            DropColumn("dbo.WardrobeItem", "Willpower");
            DropColumn("dbo.WardrobeItem", "Sneak");
            DropColumn("dbo.WardrobeItem", "SleightOfHand");
            DropColumn("dbo.WardrobeItem", "Acrobatics");
            DropColumn("dbo.WardrobeItem", "Tenacity");
            DropColumn("dbo.WardrobeItem", "Athletics");
            DropColumn("dbo.WardrobeItem", "Constitution");
            DropColumn("dbo.WardrobeItem", "Endurance");
            DropColumn("dbo.WardrobeItem", "Speed");
            DropColumn("dbo.WardrobeItem", "Fate");
            DropColumn("dbo.WardrobeItem", "Magic");
            DropColumn("dbo.WardrobeItem", "BaseProwess");
            DropColumn("dbo.WardrobeItem", "Reaction");
            DropColumn("dbo.WardrobeItem", "Dodge");
            DropColumn("dbo.WardrobeItem", "Sanity");
            DropColumn("dbo.WardrobeItem", "HitPoints");
            DropColumn("dbo.WardrobeItem", "Charisma");
            DropColumn("dbo.WardrobeItem", "Intelligence");
            DropColumn("dbo.WardrobeItem", "Agility");
            DropColumn("dbo.WardrobeItem", "Instinct");
            DropColumn("dbo.WardrobeItem", "Strength");
            DropColumn("dbo.WardrobeItem", "Health");
            DropColumn("dbo.WardrobeItem", "BlockModifier");
            DropColumn("dbo.Character", "PhysicalResistance");
            DropColumn("dbo.Character", "TempHitPoints");
            DropColumn("dbo.Character", "CurrentHitPoints");
        }
    }
}
