// <auto-generated />
namespace HomebrewRPG.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class keyforcharacterWeapon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keyforcharacterWeapon));
        
        string IMigrationMetadata.Id
        {
            get { return "202107100602349_key for characterWeapon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
