// <auto-generated />
namespace HomebrewRPG.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedstatstoweaponandwardrobe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedstatstoweaponandwardrobe));
        
        string IMigrationMetadata.Id
        {
            get { return "202107101732058_added stats to weapon and wardrobe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
